"use client";
import { Sparkles } from "lucide-react";
interface AISummaryProps {
    summary: string;
}
export default function AISummary({
    summary,
}: AISummaryProps) {
    return (
        <div className="bg-[var(--card)] border border-[var(--border)] rounded-2xl p-6">
            <div className="flex items-center gap-3 mb-5">
                <div className="w-10 h-10 rounded-xl bg-[var(--accent)]/15 flex items-center justify-center">
                    <Sparkles size={18} className="text-[var(--accent)]" />
                </div>
                <div>
                    <h3 className="text-lg font-semibold text-[var(--text-primary)]">
                        AI Summary
                    </h3>
                    <p className="text-sm text-[var(--text-secondary)]">
                        Generated by ConvertIQ
                    </p>
                </div>
            </div>
            <p className="text-[15px] leading-8 text-[var(--text-primary)]">
                {summary}
            </p>
        </div>
    );
}