'use client';

import { useEffect, useState } from 'react';

import { Sparkles, Loader2 } from 'lucide-react';

import SuggestedReplies from './SuggestedReplies';

interface AISummaryProps {
  messageId: string;
}

interface SummaryResponse {
  summary: string;

  actionItems: string[];

  priority: 'low' | 'medium' | 'high';

  suggestedReplies: string[];
}

export default function AISummary({ messageId }: AISummaryProps) {
  const [data, setData] = useState<SummaryResponse | null>(null);

  const [loading, setLoading] = useState(true);

  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let ignore = false;

    async function loadSummary() {
      try {
        setLoading(true);

        setError(null);

        const res = await fetch(`/api/email-summary/${messageId}`);

        if (!res.ok) {
          throw new Error('Failed to generate summary');
        }

        const json = await res.json();

        if (!ignore) {
          setData(json);
        }
      } catch (error: any) {
        if (!ignore) {
          setError(error.message ?? 'Something went wrong');
        }
      } finally {
        if (!ignore) {
          setLoading(false);
        }
      }
    }

    loadSummary();

    return () => {
      ignore = true;
    };
  }, [messageId]);

  return (
    <div className="bg-[var(--card)] border border-[var(--border)] rounded-2xl p-6">
      <div className="flex items-center gap-3 mb-5">
        <div className="w-10 h-10 rounded-xl bg-[var(--accent)]/15 flex items-center justify-center">
          {loading ? (
            <Loader2 size={18} className="text-[var(--accent)] animate-spin" />
          ) : (
            <Sparkles size={18} className="text-[var(--accent)]" />
          )}
        </div>

        <div>
          <h3 className="text-lg font-semibold">AI Summary</h3>

          <p className="text-sm text-[var(--text-secondary)]">
            Generated by ConvertIQ
          </p>
        </div>
      </div>

      {loading && (
        <div className="space-y-3">
          <div className="h-4 rounded bg-white/[0.05] animate-pulse" />

          <div className="h-4 rounded bg-white/[0.05] animate-pulse w-[90%]" />

          <div className="h-4 rounded bg-white/[0.05] animate-pulse w-[70%]" />
        </div>
      )}

      {!loading && error && <p className="text-sm text-red-400">{error}</p>}

      {!loading && data && (
        <div className="space-y-6">
          <p className="text-[15px] leading-8 text-[var(--text-primary)]">
            {data.summary}
          </p>

          {data.actionItems?.length > 0 && (
            <div>
              <h4 className="text-sm font-semibold mb-3">Action Items</h4>

              <ul className="space-y-2">
                {data.actionItems.map((item) => (
                  <li
                    key={item}
                    className="text-sm text-[var(--text-secondary)] flex gap-2"
                  >
                    <span>•</span>

                    <span>{item}</span>
                  </li>
                ))}
              </ul>
            </div>
          )}

          <div>
            <span className="text-sm text-[var(--text-secondary)]">
              Priority
            </span>

            <div className="mt-2">
              <span className="px-3 py-1 rounded-full text-xs bg-white/[0.04] border border-[var(--border)]">
                {data.priority}
              </span>
            </div>
          </div>
          {data.suggestedReplies?.length > 0 && (
            <div>
              {/* <h4 className="text-sm font-semibold mb-3">Suggested Replies</h4> */}
              <SuggestedReplies replies={data.suggestedReplies} />
            </div>
          )}
        </div>
      )}
    </div>
  );
}
