'use client';

import { useEffect, useState } from 'react';

import { Loader2, Copy, Check } from 'lucide-react';

interface DraftReplyProps {
  messageId: string;

  email: {
    from: string;

    subject: string;

    threadId: string;
  };
}

export default function DraftReply({
  messageId,

  email,
}: DraftReplyProps) {
  const [reply, setReply] = useState('');

  const [loading, setLoading] = useState(true);

  const [error, setError] = useState<string | null>(null);

  const [copied, setCopied] = useState(false);

  const [sending, setSending] = useState(false);

  const [sent, setSent] = useState(false);

  useEffect(() => {
    async function load() {
      try {
        setLoading(true);

        setError(null);

        const res = await fetch(`/api/email-service/draft-reply/${messageId}`);

        if (!res.ok) {
          throw new Error('Failed to generate reply');
        }

        const data = await res.json();

        setReply(data.reply);
      } catch (error: any) {
        setError(error.message ?? 'Something went wrong');
      } finally {
        setLoading(false);
      }
    }

    load();
  }, [messageId]);

  async function handleCopy() {
    await navigator.clipboard.writeText(reply);

    setCopied(true);

    setTimeout(() => {
      setCopied(false);
    }, 2000);
  }

  async function handleSend() {
    try {
      setSending(true);

      const res = await fetch(
        '/api/email-service/reply',

        {
          method: 'POST',

          headers: {
            'Content-Type': 'application/json',
          },

          body: JSON.stringify({
            to: email.from,

            subject: email.subject,

            body: reply,

            threadId: email.threadId,
          }),
        }
      );

      if (!res.ok) {
        const error = await res.json();

        console.log(error);

        throw new Error(error.error);
      }

      setSent(true);

      setTimeout(() => {
        setSent(false);
      }, 3000);
    } catch (error: any) {
      console.error(error);

      alert(error.message);
    } finally {
      setSending(false);
    }
  }

  return (
    <div className="bg-[var(--card)] border border-[var(--border)] rounded-2xl p-6">
      <div className="flex items-center justify-between mb-5">
        <div>
          <h3 className="text-lg font-semibold">AI Draft Reply</h3>

          <p className="text-sm text-[var(--text-secondary)]">
            Generated by ConvertIQ
          </p>
        </div>

        {!loading && !error && (
          <div className="flex gap-3">
            <button
              onClick={handleCopy}
              className="flex items-center gap-2 px-3 py-2 rounded-xl border border-[var(--border)] hover:bg-white/[0.03] transition"
            >
              {copied ? (
                <>
                  <Check size={16} />
                  Copied
                </>
              ) : (
                <>
                  <Copy size={16} />
                  Copy
                </>
              )}
            </button>

            <button
              onClick={handleSend}
              disabled={sending || sent}
              className="
              px-4 py-2
              rounded-xl
              bg-[var(--accent)]
              text-white
              disabled:opacity-50
              hover:opacity-90
              transition
              "
            >
              {sending ? 'Sending...' : sent ? 'Sent ✓' : 'Send'}
            </button>
          </div>
        )}
      </div>

      {loading ? (
        <div className="flex items-center gap-3 text-[var(--text-secondary)]">
          <Loader2 size={18} className="animate-spin" />
          Drafting reply...
        </div>
      ) : error ? (
        <p className="text-red-400 text-sm">{error}</p>
      ) : (
        <textarea
          value={reply}
          onChange={(e) => setReply(e.target.value)}
          className="
          w-full
          h-[220px]
          resize-none
          rounded-2xl
          bg-[var(--bg)]
          border
          border-[var(--border)]
          p-5
          outline-none
          focus:border-[var(--accent)]
          "
        />
      )}
    </div>
  );
}
