import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { DM_Serif_Display } from "next/font/google";

const dmSerif = DM_Serif_Display({
	subsets: ["latin"],
	weight: ["400"],
});

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning className={`dark ${geistSans.variable} ${geistMono.variable} h-full antialiased`}
		>
			<body className={`min-h-full flex flex-col font-[var(--font-dm-serif)]`} 
			>
				{children}
			</body>
		</html>
	);
}
